const data = require('./data')
const displaySchema = require('./display_schema')
const showValues = require('./showValues')
const scrollToAnchor = require('./scroll')
const tabs = require('./tabs')
const versionsLinks = require('./versionLinks')

versionsLinks()
tabs(data.active, data.enums, data.enumsValues)
displaySchema(data.enums).then(scrollToAnchor)
showValues(data.version)
