/* eslint-env mocha */

const assert = require('assert')
const items = require('../../../data/pc/1.20.5/items.json')
const paths = require('../../../data/dataPaths.json')
const expected = require('./fixtures/1.20.5-max-damage.json')
const enchantments = require('../../../data/pc/1.20.5/enchantments.json')

describe('1.20.5/1.20.6 item durability', () => {
  it('matches the max_damage components generated by vanilla', () => {
    const actual = Object.fromEntries(items.filter(item => item.maxDurability !== undefined).map(item => [item.name, item.maxDurability]))
    assert.deepStrictEqual(actual, expected)
  })

  it('uses the corrected data for both releases', () => {
    assert.strictEqual(paths.pc['1.20.5'].items, 'pc/1.20.5')
    assert.strictEqual(paths.pc['1.20.6'].items, 'pc/1.20.5')
  })

  it('uses the same category names as the versioned enchantment registry', () => {
    for (const [itemName, enchantmentName] of [['diamond_sword', 'unbreaking'], ['iron_pickaxe', 'efficiency']]) {
      const item = items.find(item => item.name === itemName)
      const enchantment = enchantments.find(enchantment => enchantment.name === enchantmentName)
      assert.ok(item.enchantCategories.includes(enchantment.category), `${itemName}/${enchantmentName}`)
    }
  })

  it('includes native repair ingredients for wolf armor and the mace', () => {
    assert.deepStrictEqual(items.find(item => item.name === 'wolf_armor').repairWith, ['armadillo_scute'])
    assert.deepStrictEqual(items.find(item => item.name === 'mace').repairWith, ['breeze_rod'])
  })
})
