// This is a simple tool to add itemMultiplier & bookMultiplier to enchantments.json files that were generated automatically
// The constants.js was generated by regexing this page: https://minecraft.gamepedia.com/Anvil_mechanics#Costs_for_combining_enchantments
const constants = require('./constants.js')
const newData = require('./in.json')
const fs = require('fs')

newData.forEach((el, ix) => {
  const { itemMultiplier, bookMultiplier } = constants.find(x => el.displayName === x.name)
  newData[ix].itemMultiplier = itemMultiplier
  newData[ix].bookMultiplier = bookMultiplier
})

fs.writeFileSync('out.json', JSON.stringify(newData, null, 2))
console.log('done!')
