module.exports = [
  { id: 0, name: 'Protection', maxLevel: 'IV', itemMultiplier: 1, bookMultiplier: 1 },
  { id: 1, name: 'Fire Protection', maxLevel: 'IV', itemMultiplier: 2, bookMultiplier: 1 },
  { id: 2, name: 'Feather Falling', maxLevel: 'IV', itemMultiplier: 2, bookMultiplier: 1 },
  { id: 3, name: 'Blast Protection', maxLevel: 'IV', itemMultiplier: 4, bookMultiplier: 2 },
  { id: 4, name: 'Projectile Protection', maxLevel: 'IV', itemMultiplier: 2, bookMultiplier: 1 },
  { id: 5, name: 'Thorns', maxLevel: 'III', itemMultiplier: 8, bookMultiplier: 4 },
  { id: 6, name: 'Respiration', maxLevel: 'III', itemMultiplier: 4, bookMultiplier: 2 },
  { id: 7, name: 'Depth Strider', maxLevel: 'III', itemMultiplier: 4, bookMultiplier: 2 },
  { id: 8, name: 'Aqua Affinity', maxLevel: 'I', itemMultiplier: 4, bookMultiplier: 2 },
  { id: 9, name: 'Sharpness', maxLevel: 'V', itemMultiplier: 1, bookMultiplier: 1 },
  { id: 10, name: 'Smite', maxLevel: 'V', itemMultiplier: 2, bookMultiplier: 1 },
  { id: 11, name: 'Bane of Arthropods', maxLevel: 'V', itemMultiplier: 2, bookMultiplier: 1 },
  { id: 12, name: 'Knockback', maxLevel: 'II', itemMultiplier: 2, bookMultiplier: 1 },
  { id: 13, name: 'Fire Aspect', maxLevel: 'II', itemMultiplier: 4, bookMultiplier: 2 },
  { id: 14, name: 'Looting', maxLevel: 'III', itemMultiplier: 4, bookMultiplier: 2 },
  { id: 15, name: 'Efficiency', maxLevel: 'V', itemMultiplier: 1, bookMultiplier: 1 },
  { id: 16, name: 'Silk Touch', maxLevel: 'I', itemMultiplier: 8, bookMultiplier: 4 },
  { id: 17, name: 'Unbreaking', maxLevel: 'III', itemMultiplier: 2, bookMultiplier: 1 },
  { id: 18, name: 'Fortune', maxLevel: 'III', itemMultiplier: 4, bookMultiplier: 2 },
  { id: 19, name: 'Power', maxLevel: 'V', itemMultiplier: 1, bookMultiplier: 1 },
  { id: 20, name: 'Punch', maxLevel: 'II', itemMultiplier: 4, bookMultiplier: 2 },
  { id: 21, name: 'Flame', maxLevel: 'I', itemMultiplier: 4, bookMultiplier: 2 },
  { id: 22, name: 'Infinity', maxLevel: 'I', itemMultiplier: 8, bookMultiplier: 4 },
  { id: 23, name: 'Luck of the Sea', maxLevel: 'III', itemMultiplier: 4, bookMultiplier: 2 },
  { id: 24, name: 'Lure', maxLevel: 'III', itemMultiplier: 4, bookMultiplier: 2 },
  { id: 25, name: 'Frost Walker', maxLevel: 'II', itemMultiplier: 4, bookMultiplier: 2 },
  { id: 26, name: 'Mending', maxLevel: 'I', itemMultiplier: 4, bookMultiplier: 2 },
  { id: 27, name: 'Curse of Binding', maxLevel: 'I', itemMultiplier: 8, bookMultiplier: 4 },
  { id: 28, name: 'Curse of Vanishing', maxLevel: 'I', itemMultiplier: 8, bookMultiplier: 4 },
  { id: 29, name: 'Impaling', maxLevel: 'V', itemMultiplier: 4, bookMultiplier: 2 },
  { id: 30, name: 'Riptide', maxLevel: 'III', itemMultiplier: 4, bookMultiplier: 2 },
  { id: 31, name: 'Loyalty', maxLevel: 'III', itemMultiplier: 1, bookMultiplier: 1 },
  { id: 32, name: 'Channeling', maxLevel: 'I', itemMultiplier: 8, bookMultiplier: 4 },
  { id: 33, name: 'Multishot', maxLevel: 'I', itemMultiplier: 4, bookMultiplier: 2 },
  { id: 34, name: 'Piercing', maxLevel: 'IV', itemMultiplier: 1, bookMultiplier: 1 },
  { id: 35, name: 'Quick Charge', maxLevel: 'III', itemMultiplier: 2, bookMultiplier: 1 },
  { id: 36, name: 'Soul Speed', maxLevel: 'III', itemMultiplier: 8, bookMultiplier: 4 },
  { id: 37, name: 'Sweeping Edge', maxLevel: 'III', itemMultiplier: 4, bookMultiplier: 2 }
]
